version: '3.8'

services:
  app:
    build: .
    environment:
      - MONGODB_URL=mongodb://database:27017
    depends_on:
      - database

  database:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

